"""Signal domain models."""

from enum import Enum
from typing import Dict, List, Optional, Any
from pydantic import BaseModel, Field


class SignalDirection(str, Enum):
    LONG = "LONG"
    SHORT = "SHORT"
    NO_TRADE = "NO_TRADE"


class SignalType(str, Enum):
    MARKET = "MARKET"
    LIMIT = "LIMIT"


class TargetCandidate(BaseModel):
    name: str = "TP1"
    price: float
    reward_r: float
    description: Optional[str] = None


class StopCandidate(BaseModel):
    name: str = "STRUCTURAL"
    price: float
    risk_distance: float
    description: Optional[str] = None


class SignalCandidate(BaseModel):
    """Structured signal candidate generated by strategy logic."""
    signal_id: str
    strategy_id: str
    strategy_version: str
    timestamp: int = Field(description="Information availability timestamp in ms UTC")
    symbol: str = "ETHUSDT"
    timeframe: str = "15m"
    direction: SignalDirection
    entry_type: SignalType = SignalType.MARKET
    entry_price: float
    entry_zone: Optional[tuple[float, float]] = None
    stop_candidate: Optional[StopCandidate] = None
    target_candidates: List[TargetCandidate] = Field(default_factory=list)
    calculated_rr: float = 0.0
    expiry_timestamp: Optional[int] = None
    evidence: List[str] = Field(default_factory=list)
    feature_snapshot: Dict[str, Any] = Field(default_factory=dict)
    diagnostics: Dict[str, Any] = Field(default_factory=dict)

    @property
    def stop_loss(self) -> Optional[float]:
        return self.stop_candidate.price if self.stop_candidate else None

    @property
    def take_profit_1(self) -> Optional[float]:
        return self.target_candidates[0].price if self.target_candidates else None

    @property
    def risk_reward_ratio(self) -> float:
        return self.calculated_rr
